
version: '3.1'
services:
  db:
    container_name: Mongo-db
    image: mongo:latest
    restart: always
    environment:
      - DB_AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - DB_AWS_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - 27020:27017
